spring:
  application:
    name: demo-app
  profiles:
    active: ml
  python:
    cache:
      enabled: true
    executor:
      type: grpc
      grpc:
        token: secret
  cache:
    type: caffeine
    cache-names: myCache, ${spring.python.cache.name.file-bodies}, ${spring.python.cache.name.file-paths}, ${spring.python.cache.name.resolver}, ${spring.python.cache.name.executor}, ${spring.python.cache.name.processor}
  docker:
    compose:
      file: ./demo-app/docker-compose.yaml